const INCORRECT_DATA_ERROR = 400;
const AUTHORISATION_ERROR = 401;
const NO_DATA_ERROR = 404;
const DEFAULT_ERROR = 500;

module.exports = {
  INCORRECT_DATA_ERROR,
  AUTHORISATION_ERROR,
  NO_DATA_ERROR,
  DEFAULT_ERROR,
};
